name: NBA model retrain

on:
  schedule:
  - cron: "0 10 * * *"

  workflow_dispatch:

jobs:
  active_tenants_json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"tenant\":\"foo\",\"config\":\"Debug\"},{\"tenant\":\"bar\",\"config\":\"Release\"}]}"
  
  run_model_trainings:
    needs: active_tenants_json
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.active_tenants_json.outputs.matrix)}}
    steps:
    - name: build_image
      run: docker build -t worker .

    - name: build_image
      env:
        TENANT: ${{ matrix.tenant }}
      run: docker run worker
