name: NBA model retrain

on:
  schedule:
  - cron: "0 10 * * *"

  workflow_dispatch:

jobs:
  collect_branches:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}


    steps:
    - uses: actions/checkout@v2

    - name: build_image
      run: docker build -t worker .

    - id: set-matrix
      run: docker run worker python collect_branches.py


  execute_branches:
    needs: collect_branches
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJSON(needs.collect_branches.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v2

    - name: build_image
      run: docker build -t worker .

    - name: run_task
      run: docker run --env BRANCH=${{ matrix.branch }} worker
